!a       = "http://www.amazon.co.uk/s/?field-keywords="
!an      = "http://antinews.nushackers.org/search?q="
!e       = "http://www.erowid.org/search.php?q="
!eb      = "http://rogerebert.suntimes.com/section/bossv2?q="
!etym    = "http://etymonline.com/index.php?search="
!ex      = "http://examine.com/search.php?q="
!examine = "http://examine.com/search.php?q="
!gs      = "http://grooveshark.com/#!/search?q="
!gw      = "https://duckduckgo.com/?kp=-1&kz=-1&kf=-1&kg=p&ks=m&kw=s&km=l&ku=1&ko=-1&k4=-1&ke=-1&kk=s&kr=-1&kq=-1&k1=-1&kx=r&q=site%3Agwern.net+"
!it      = "http://www.indietorrents.com/torrents.php?searchstr="
!lg      = "http://gen.lib.rus.ec/search?nametype=orig&column[]=title&req="
!libgen  = "http://gen.lib.rus.ec/search?nametype=orig&column[]=title&req="
!lw      = "http://lesswrong.com/search/results?cx=015839050583929870010%3A-802ptn4igi&cof=FORID%3A11&q="
!nlb     = "http://nlbsearchplus.nlb.gov.sg/primo_library/libweb/action/search.do?fn=search&srt=rank&fctV=physical_resources&vl(freeText0)="
!nyaa    = "http://www.nyaa.eu/?page=search&term="
!phy     = "http://www.physics.thetangentbundle.net/wiki/Special:Search?search="
!qs      = "http://quantifiedself.com/?s="
!s       = "http://scholar.google.com.sg/scholar?q="
!sch     = "http://scholar.google.com.sg/scholar?q="
!phil    = "http://plato.stanford.edu/search/searcher.py?query="
!sep     = "http://plato.stanford.edu/search/searcher.py?query="
!yum     = "http://www.yummly.com/recipes?q="
!yummly  = "http://www.yummly.com/recipes?q="
!ddg     = "https://duckduckgo.com/?kp=-1&kz=-1&kf=-1&kg=p&ks=m&kw=s&km=l&ku=1&ko=-1&k4=-1&ke=-1&kk=s&kr=-1&kq=-1&k1=-1&kx=r&q="

# vim:set ft=yaml: ;-)
